import React, { useState, useEffect } from 'react';
import api from '../services/api';
import { motion, AnimatePresence } from 'framer-motion';
import { Button } from '../components/ui/Button';
import { Inbox, FileText, Printer, X } from 'lucide-react';

const STATUS_COLOR = { Generated: 'blue', Sent: 'emerald', Replied: 'violet', Draft: 'slate' };

export default function NoticesEngine({ caseId, onClose }) {
    const [dispatchList, setDispatchList] = useState([]);
    const [selectedNoticeHtml, setSelectedNoticeHtml] = useState(null);

    useEffect(() => {
        const fetchDispatch = async () => {
            try {
                const res = await api.get(`/notices/dispatch/${caseId}`);
                if (res.data.success) setDispatchList(res.data.data);
            } catch {}
        };
        fetchDispatch();
    }, [caseId]);

    return (
        <div className="fixed inset-0 z-50 bg-slate-900/40 backdrop-blur-sm flex items-center justify-center p-4">
            <motion.div
                initial={{ opacity: 0, scale: 0.95 }}
                animate={{ opacity: 1, scale: 1 }}
                exit={{ opacity: 0, scale: 0.95 }}
                className="bg-white rounded-2xl shadow-2xl w-full max-w-6xl flex flex-col overflow-hidden max-h-[90vh]"
            >
                <div className="flex items-center justify-between p-6 bg-slate-900 text-white shrink-0">
                    <div className="flex items-center gap-3">
                        <Inbox size={24} className="text-blue-400" />
                        <div>
                            <h2 className="text-xl font-black uppercase tracking-widest">Dispatch Register</h2>
                            <p className="text-xs text-slate-400 font-bold uppercase tracking-widest mt-1">
                                View & Print Generated Official Records
                            </p>
                        </div>
                    </div>
                    <button onClick={onClose} className="p-2 hover:bg-slate-800 rounded-xl transition-colors">
                        <X size={20} />
                    </button>
                </div>

                <div className="bg-white flex-1 overflow-auto relative">
                    <div className="p-8 min-h-[500px]">
                        <div className="flex items-center gap-3 mb-6 border-b border-slate-100 pb-4">
                            <Inbox className="text-blue-600" size={20} />
                            <h3 className="text-base font-bold text-slate-900 uppercase">Dispatch Register</h3>
                        </div>
                        
                        {dispatchList.length === 0 ? (
                            <div className="py-20 text-center">
                                <FileText className="mx-auto text-slate-200 mb-4" size={48} />
                                <p className="text-slate-400 text-xs font-bold uppercase tracking-widest">No notices generated yet for this case.</p>
                            </div>
                        ) : (
                            <div className="overflow-x-auto">
                                <table className="w-full text-xs">
                                    <thead>
                                        <tr className="border-b border-slate-100">
                                            {['Dispatch No', 'Bank / Entity', 'Notice Type', 'Accounts', 'Generated By', 'Date', 'Status', ''].map(h => (
                                                <th key={h} className={`text-left p-3 text-[9px] font-black text-slate-400 uppercase tracking-widest ${h === '' ? 'text-right' : ''}`}>{h}</th>
                                            ))}
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {dispatchList.map(d => (
                                            <tr key={d.notice_id} 
                                                className="border-b border-slate-50 hover:bg-slate-50 cursor-pointer transition-all"
                                                onClick={() => setSelectedNoticeHtml(d.notice_content)}
                                            >
                                                <td className="p-3 font-mono font-bold text-blue-700 text-[10px]">{d.dispatch_no}</td>
                                                <td className="p-3 font-bold text-slate-900">{d.bank_name}</td>
                                                <td className="p-3 text-slate-600">{d.notice_type_code?.replace(/_/g, ' ')}</td>
                                                <td className="p-3 text-slate-500">{d.selected_accounts?.length || 0} accts</td>
                                                <td className="p-3 text-slate-500">{d.issued_by}</td>
                                                <td className="p-3 text-slate-400">{new Date(d.created_at).toLocaleDateString()}</td>
                                                <td className="p-3">
                                                    <span className={`px-2 py-1 rounded-full text-[8px] font-black uppercase bg-${STATUS_COLOR[d.status] || 'slate'}-50 text-${STATUS_COLOR[d.status] || 'slate'}-600 border border-${STATUS_COLOR[d.status] || 'slate'}-100`}>
                                                        {d.status}
                                                    </span>
                                                </td>
                                                <td className="p-3 text-right">
                                                    <Button variant="ghost" className="h-8 w-8 p-0" onClick={(e) => {
                                                        e.stopPropagation();
                                                        const printWindow = window.open('', '_blank');
                                                        printWindow.document.write('<html><head><title>' + d.dispatch_no + '</title></head><body style="margin:0;padding:20mm;">' + d.notice_content + '</body></html>');
                                                        printWindow.document.close();
                                                        setTimeout(() => { printWindow.print(); }, 500);
                                                    }}>
                                                        <Printer size={14} className="text-slate-400 hover:text-blue-600" />
                                                    </Button>
                                                </td>
                                            </tr>
                                        ))}
                                    </tbody>
                                </table>
                            </div>
                        )}
                    </div>
                </div>
            </motion.div>

            <AnimatePresence>
                {selectedNoticeHtml && (
                    <motion.div 
                        initial={{ opacity: 0, scale: 0.95 }}
                        animate={{ opacity: 1, scale: 1 }}
                        exit={{ opacity: 0, scale: 0.95 }}
                        className="fixed inset-0 z-[60] bg-slate-900/80 backdrop-blur-sm flex items-center justify-center p-8"
                        onClick={() => setSelectedNoticeHtml(null)}
                    >
                        <div 
                            className="bg-white w-[210mm] min-h-[297mm] h-[90vh] overflow-auto shadow-2xl relative"
                            onClick={e => e.stopPropagation()}
                        >
                            <button onClick={() => setSelectedNoticeHtml(null)} className="absolute top-4 right-4 p-2 bg-rose-50 text-rose-600 hover:bg-rose-100 rounded-full transition-colors z-10 shadow-sm border border-rose-200">
                                <X size={20} />
                            </button>
                            <div className="p-12 origin-top" dangerouslySetInnerHTML={{ __html: selectedNoticeHtml }} />
                        </div>
                    </motion.div>
                )}
            </AnimatePresence>
        </div>
    );
}
