; CyberPS Investigation Hunter - Inno Setup Script
; Generated by CyberPS Build System

#define AppName "CyberPS"
#define AppVersion "1.0.2"
#define AppPublisher "Akshay Dadhich"
#define AppURL "https://github.com/AkshayDadhich/CyberPSWebsite"
#define AppExeName "CyberPS.exe"

[Setup]
AppId={{6E4B2A3C-9F1D-4E8B-A7C2-3D5F6E8B9A1C}
AppName={#AppName}
AppVersion={#AppVersion}
AppPublisher={#AppPublisher}
AppPublisherURL={#AppURL}
AppSupportURL={#AppURL}
AppUpdatesURL={#AppURL}
DefaultDirName={autopf}\CyberPS
DefaultGroupName={#AppName}
DisableProgramGroupPage=yes
OutputDir=..\dist_installer
OutputBaseFilename=CyberPS_Setup_v1.0.2
Compression=lzma2/ultra64
SolidCompression=yes
WizardStyle=modern
PrivilegesRequired=admin
ArchitecturesInstallIn64BitMode=x64
UninstallDisplayIcon={app}\CyberPS.exe
SetupIconFile=..\installer\icon.ico
WizardImageFile=..\installer\wizard_banner.bmp
WizardSmallImageFile=..\installer\wizard_small.bmp
LicenseFile=..\installer\LICENSE.txt
InfoBeforeFile=..\installer\README_INSTALL.txt
DisableWelcomePage=no
CloseApplications=yes
RestartIfNeededByRun=no

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "startupicon"; Description: "Start CyberPS automatically with Windows"; GroupDescription: "Startup Options:"; Flags: unchecked

[Files]
; Main launcher EXE
Source: "..\dist_build\CyberPS.exe"; DestDir: "{app}"; Flags: ignoreversion

; Updater EXE (separate process for safe file replacement)
Source: "..\dist_build\updater.exe"; DestDir: "{app}"; Flags: ignoreversion

; Version manifest
Source: "..\version.json"; DestDir: "{app}"; Flags: ignoreversion

; Backend compiled executable
Source: "..\dist_build\backend\backend.exe"; DestDir: "{app}\backend"; Flags: ignoreversion
Source: "..\dist_build\backend\eng.traineddata"; DestDir: "{app}\backend"; Flags: ignoreversion
Source: "..\dist_build\backend\hin.traineddata"; DestDir: "{app}\backend"; Flags: ignoreversion
Source: "..\dist_build\backend\seed_data.json"; DestDir: "{app}\backend"; Flags: ignoreversion onlyifdoesntexist

; FIR Extractor Script
Source: "..\dist_build\scripts\fir_extractor.exe"; DestDir: "{app}\backend\scripts"; Flags: ignoreversion

; Frontend compiled static files
Source: "..\dist_build\frontend\dist\*"; DestDir: "{app}\frontend\dist"; Flags: ignoreversion recursesubdirs createallsubdirs

; Ramail Python Service
Source: "..\dist_build\ramail\ramail.exe"; DestDir: "{app}\ramail"; Flags: ignoreversion

; Portable Tools (Tesseract + Poppler) - pre-bundled
Source: "..\bin\*"; DestDir: "{app}\bin"; Flags: ignoreversion recursesubdirs createallsubdirs

; Bank mail list data
Source: "..\bankmaillist.json"; DestDir: "{app}"; Flags: ignoreversion

; Database schema
Source: "..\schema.sql"; DestDir: "{app}"; Flags: ignoreversion

; Environment template (user will fill DB credentials)
Source: "..\installer\env_template.txt"; DestDir: "{app}"; DestName: ".env"; Flags: ignoreversion onlyifdoesntexist

; Uploads folder placeholder files
; IMPORTANT: onlyifdoesntexist ensures existing user files (FIRs, notices, evidence) are NEVER overwritten
Source: "..\installer\placeholder.txt"; DestDir: "{app}\uploads\fir";      DestName: ".gitkeep"; Flags: onlyifdoesntexist
Source: "..\installer\placeholder.txt"; DestDir: "{app}\uploads\notices";  DestName: ".gitkeep"; Flags: onlyifdoesntexist
Source: "..\installer\placeholder.txt"; DestDir: "{app}\uploads\excels";   DestName: ".gitkeep"; Flags: onlyifdoesntexist
Source: "..\installer\placeholder.txt"; DestDir: "{app}\uploads\evidence"; DestName: ".gitkeep"; Flags: onlyifdoesntexist

[Dirs]
; DATA DIRECTORIES — preserved across updates and uninstall
; Flags: uninsneveruninstall ensures Inno Setup NEVER deletes these even on full uninstall
Name: "{app}\uploads\fir";      Flags: uninsneveruninstall
Name: "{app}\uploads\notices"; Flags: uninsneveruninstall
Name: "{app}\uploads\excels";  Flags: uninsneveruninstall
Name: "{app}\uploads\evidence"; Flags: uninsneveruninstall
; App directories (can be removed on uninstall)
Name: "{app}\Temp\Updates"
Name: "{app}\Backup"
Name: "{app}\logs"
Name: "{app}\ramail\attachments"
Name: "{app}\ramail\inbox"

[Icons]
Name: "{group}\{#AppName}"; Filename: "{app}\CyberPS.exe"; IconFilename: "{app}\CyberPS.exe"
Name: "{group}\Configure CyberPS (.env)"; Filename: "notepad.exe"; Parameters: "{app}\.env"; IconFilename: "{sys}\notepad.exe"
Name: "{group}\{cm:UninstallProgram,{#AppName}}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#AppName}"; Filename: "{app}\CyberPS.exe"; Tasks: desktopicon; IconFilename: "{app}\CyberPS.exe"
Name: "{userstartup}\{#AppName}"; Filename: "{app}\CyberPS.exe"; Tasks: startupicon

[Run]
; Open config file for user to fill in DB credentials
Filename: "notepad.exe"; Parameters: "{app}\.env"; Description: "Configure database settings (.env file)"; Flags: nowait postinstall skipifsilent unchecked
; Launch app after install
Filename: "{app}\CyberPS.exe"; Description: "Launch {#AppName}"; Flags: nowait postinstall skipifsilent

[UninstallRun]
Filename: "taskkill"; Parameters: "/f /im backend.exe"; Flags: runhidden
Filename: "taskkill"; Parameters: "/f /im ramail.exe"; Flags: runhidden

[Code]
function InitializeSetup(): Boolean;
begin
  Result := True;
end;

procedure CurStepChanged(CurStep: TSetupStep);
begin
  if CurStep = ssPostInstall then
  begin
    // Uploads, notices, and evidence folders are NEVER touched by installer.
    // They use Flags: uninsneveruninstall so even uninstall preserves case data.
  end;
end;

//
// PreventDataLoss — called before uninstall.
// Shows a warning if uploads folder contains user data.
//
function InitializeUninstall(): Boolean;
var
  FirCount: Integer;
  Msg: String;
begin
  Result := True;
  // Warn if user has FIR uploads that will NOT be deleted (they are preserved)
  Msg := 'CyberPS will be uninstalled.' + #13#10 + #13#10 +
         'Your case data (uploaded FIRs, notices, evidence files) is stored' + #13#10 +
         'separately and will NOT be deleted.' + #13#10 + #13#10 +
         'Database records remain on your SQL Server.' + #13#10 + #13#10 +
         'Continue with uninstall?';
  if MsgBox(Msg, mbConfirmation, MB_YESNO) = IDNO then
    Result := False;
end;
